server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/dbvote?createDatabaseIfNotExist=true&useSSL=false&useTimezone=true&serverTimezone=UTC
  jpa:
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate.format_sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  cloud:
    stream:
      bindings:
        resultVoteChannelOutput:
          destination: result-vote-exchange
          contentType: application/json
        resultVoteChannelInput:
          destination: result-vote-exchange
          contentType: application/json
          consumer:
            max-attempts: 1

  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: 5672
    username: guest
    password: guest

info:
  app:
    name: 'Votes Application'

url-cpf-integration: "https://user-info.herokuapp.com/users/"