server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost/dbvote?createDatabaseIfNotExist=true&useSSL=false&useTimezone=true&serverTimezone=UTC
  jpa:
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

info:
  app:
    name: 'Votes Application'

url-cpf-integration: "https://user-info.herokuapp.com/users/"